name: LobbySystem
authors:
  - alpharout
  - CRAFTagain
version: 0.01
main: de.craftagain.lobbysystem.main.LobbySystem

commands:
  info:
    usage: /info
    description: This command shows you the basic information about this plugin
    permission: System.info
  settings:
    name: settings
    description: Edit main cords.